# Generated by Django 6.0.6 on 2026-09-28 04:26

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="What customers type. Letters, digits and hyphens; capitals don't matter.", max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Za-z0-9-]+$', 'Use only letters, digits and hyphens.')])),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percent off'), ('FIXED', 'Fixed amount off')], default='PERCENT', max_length=7)),
                ('value', models.DecimalField(decimal_places=2, help_text='A percent (up to 100) or a dollar amount, per the type. A dollar amount comes off once per order.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Counts only the products the coupon covers.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Minimum spend')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts')),
                ('expires_at', models.DateTimeField(verbose_name='Expires')),
                ('max_uses_per_customer', models.PositiveIntegerField(blank=True, default=1, help_text='Leave empty for unlimited.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Uses per customer')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total uses')),
                ('is_active', models.BooleanField(default=True, help_text='Switch off to stop a code at once, whatever its dates.', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Leave empty to discount the whole order.', related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['-starts_at', 'code'],
                'permissions': [('manage_coupons', 'Can manage coupons')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('code',), name='unique_unarchived_coupon_code', violation_error_message='That code is already in use by another coupon.')],
            },
        ),
    ]
